---
title: "Module 2: Data Management"
author: "pravesh"
date: "2020-09-18"
output: html_document
---

## 2.1 Data transformation
In this lecture we shall cover: Data transformation: arithmetic operation- addition, subtraction, multiplication, log transformation, exponential, squaring and square root, indices. Along with these topics we shall also discuss copy-paste and transpose cells with an example as an extension/supplement to the earlier lecture.

<iframe width="560" height="315" src="https://www.youtube.com/embed/RWCiPE5NzO8" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

- Download the file [Pastespecial.xlsx](Pastespecial.xlsx) that is used in the video and practice.
- Exercise:
    - The [Mavs.xlsx](Mavs.xlsx) file contains statistics for the great 2002–2003 Dallas Mavericks basketball team. Player names are listed in column A, statistical categories are listed in row 3, and statistical results are listed in rows 4–20. Change the worksheet so that all player names are listed in the same row and all statistical categories are listed in the same column.
    - The [Productpaste.xlsx](Productpaste.xlsx) file contains data on quarterly sales for four products. Copy this data to another range so that quarterly sales are read across instead of down. Link your copied data to the original data so that your computation of annual sales in the copied data range reflect changes entered in rows 5–8.
    
## 2.2 Importing and editing data from text files/documents.
This lecture will focus on importing data from text files and editing text data to perform mathematical operations.

<iframe width="560" height="315" src="https://www.youtube.com/embed/OsRHFUAn3vc" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

- Download the file [Lineupsch38.docx](Lineupsch38.docx) that is used in the video and practice.
- Exercise: The [Kingslineups.docx](Kingslineups.docx) file contains performance ratings for some of the Sacramento Kings lineups. Import this data into Excel.

## 2.3 Creating named ranges.
In this lecture video we shall talk about creating named ranges and operations on named ranges.

<iframe width="560" height="315" src="https://www.youtube.com/embed/uRci9PnZQ7U" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

- Download the file [Historicalinvest.xlsx](Historicalinvest.xlsx) that is used in the video and practice.
- Exercise:
    - Use the [States.xlsx](States.xlsx) file to calculate the total sales in Arizona, California, Montana, New York, and New Jersey. Compute the total sales in a form such as AZ+CA+MT+NY+NJ instead of SUM(A21:A25).
    
## 2.4.1 `IF()` statement (Part - 1)
In this video we shall cover `IF()`, nested-`IF()`, and `AND()` functions.

<iframe width="560" height="315" src="https://www.youtube.com/embed/8Wx5C_8LsKM" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

## 2.4.2 `IF()` statement (Part -2)
This video is the second part explaining the use of `IF()` function. Here we will learn the use of `IF()` function in combination with some useful functions like `ROW()` and `MOD()`. 

<iframe width="560" height="315" src="https://www.youtube.com/embed/inBN7VsJtN8" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

- Download the files [Ifstatement.xlsx](Ifstatement.xlsx) and [Toyrev.xlsx](Toyrev.xlsx) used in the videos and practice.
- Exercises:
  - Some rows of column C of the [Problem28data.xlsx](Problem28data.xlsx) file contain the word *and*. Create formulas in column D that place an X in a row of column D if and only if column C in that row contains the word *and*.
  - The [Addresses.xlsx](Addresses.xlsx) file gives people’s names on one line, their street address on the next line, and their city, state, and ZIP code on the following line. How could you put each person’s information on one line?
  - A major drug company is trying to determine the correct plant capacity for a new drug. A unit of annual capacity can be built for a cost of $\$10$. Each unit of the drug sells for $\$12$ and incurs variable costs of $\$2$. The drug will be sold for 10 years. Develop a worksheet that computes the company’s 10-year profit, given the chosen annual capacity level and the annual demand for the drug. Assume demand for the drug is the same each year. You can ignore the time value of money in this problem.

## 2.5 The `COUNTIF()`, `COUNTIFS()`, `COUNT()`, `COUNTA()`, and `COUNTBLANK()` functions.
In the following two part videos we shall cover the use of the `COUNTIF()`, `COUNTIFS()`, `COUNT()`, `COUNTA()`, and `COUNTBLANK()` functions.

<iframe width="560" height="315" src="https://www.youtube.com/embed/IN-aQLLs1N8" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

## 2. Lookup functions.
In this video we shall talk about the `VLOOKUP()` function.

<iframe width="560" height="315" src="https://www.youtube.com/embed/dO0o9tVw38I" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

- Download video practice file [Lookup.xlsx](Lookup.xlsx)
- Exercise:
    - You are thinking of advertising Microsoft products on a sports telecast. As you buy more ads, the price of each ad decreases as shown in the following table:
```{r, warning=FALSE, message=FALSE, echo=FALSE, fig.align='center'}
library(tidyverse)
data.frame(`Number of ads` = c("1-5", "6-10", "11-20", "21 and higher"),
           `Price per ad` = c("$12,000","$11,000", "$10,000", "$9,000")) %>%
  knitr::kable() %>% 
  kableExtra::kable_styling(bootstrap_options = c("striped", "hover"), full_width = FALSE)
```
      
  For example, if you buy 8 ads, you pay `$11,000` per ad, but if you buy 14 ads, you pay `$10,000` per ad. Write a formula that yields the total cost of purchasing any number of ads.
  
  - The [Lookupmultiplecolumns.xlsx](Lookupmultiplecolumns.xlsx) file contains information about several sales made at an electronics store. A salesperson’s name will be entered in B17. Write an Excel formula that can be copied from C17 to D17:F17 that extracts each salesperson’s radio sales to C17, TV sales to D17, printer sales to E17, and CD sales to F17.

